### ISSUE TITLE
第二章创建 client错误

### ISSUE THREAD

**Issue by donglijie001** [HelloGitHub-Team/HelloZooKeeper#10]
ZooKeeper client = new ZooKeeper("127.0.0.1:2181/鸡太美", 3000, null); 这行代码，如果一开始没有创建 /鸡太美这个路径的话，在执行下面的创建/更新视频、/更新视频/跳舞、/更新视频/跳舞/20201101 路径的时候会报错，

**Comment by kaixinbaba** [comment]
对不起，现在才回复。谢谢你的指正，我在文章中没有明确说明出这个，感谢
