### ISSUE TITLE
问题：介绍选举文章中的问题

### ISSUE THREAD

**Issue by zhouyijiaren** [HelloGitHub-Team/HelloZooKeeper#2]
1. Long.MIN_VALUE。zxid整体是64位的，前32位是epoch，后32位是计数。那么Observer选举LOOKING时，为什么epoch要用Long.MIN_VALUE不应该是Integer.MIN_VALUE吗？
2. 另外还有一个问题，这是ZAB协议吗？还是Paxos协议呢？

**Comment by kaixinbaba** [comment]
> 1. Long.MIN_VALUE。zxid整体是64位的，前32位是epoch，后32位是计数。那么Observer选举LOOKING时，为什么epoch要用Long.MIN_VALUE不应该是Integer.MIN_VALUE吗？
![image](https://user-images.githubusercontent.com/22809336/112820730-7b2f1f00-90b8-11eb-9ade-6b439f9cbba6.png)
源码里是通过这种方式去获取 myid、zxid、epoch 的，这 3 个字段就是被定义成 `long` 所以就是 `Long.MIN_VALUE`


> 2. 另外还有一个问题，这是ZAB协议吗？还是Paxos协议呢？
应该是 ZAB 协议，ZAB 协议可以看成是 ZooKeeper 根据 Paxos 协议的具体实现（至少我是这么理解的），我其实也很难用很学术的语句去描述整个过程，我的文章也只挑选了我认为比较重要的部分进行讲解。
