### ISSUE TITLE
关于第二节的 chroot

### ISSUE THREAD

**Issue by liujunjia1996** [HelloGitHub-Team/HelloZooKeeper#3]
>要操作 ZK 首先得先创建一个客户端对象，我们以鸡太美为例
`ZooKeeper client = new ZooKeeper("127.0.0.1:2181/鸡太美", 3000, null);`
`ZooKeeper`第一个字符串就是连接的服务端地址，**`/` 后面就是 `chroot`**， 就是小故事里的标签，之后该客户端所有的操作都会以`/鸡太美`作为顶层路径去处理。

`/`后面准确的讲应该是根目录吧，`chroot`是`change root`的简写，是一个动词，用在这感觉不合适

**Comment by kaixinbaba** [comment]
chroot是官方的名字，我理解是child root，至于动词名词，太咬文嚼字了，没必要



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘骏佳 ***@***.***&gt;
发送时间: 2021年4月11日 22:46
收件人: HelloGitHub-Team/HelloZooKeeper ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[HelloGitHub-Team/HelloZooKeeper] 关于第二节的 chroot (#3)





  
要操作 ZK 首先得先创建一个客户端对象，我们以鸡太美为例
 ZooKeeper client = new ZooKeeper("127.0.0.1:2181/鸡太美", 3000, null);
 ZooKeeper第一个字符串就是连接的服务端地址，/ 后面就是 chroot， 就是小故事里的标签，之后该客户端所有的操作都会以/鸡太美作为顶层路径去处理。
  
/后面准确的讲应该是根目录吧，chroot是change root的简写，是一个动词，用在这感觉不合适

**Comment by liujunjia1996** [comment]
这是我在 zk 官网看的，大致的意思就是在连接字符串后面添加的路径，zk 内部会做一个 chroot 操作，使得该连接的所有节点都以这个路径为根目录
>Added in 3.2.0: An optional "chroot" suffix may also be appended to the connection string. This will run the client commands while interpreting all paths relative to this root (similar to the unix chroot command). If used the example would look like: "127.0.0.1:4545/app/a" or "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002/app/a" where the client would be rooted at "/app/a" and all paths would be relative to this root - ie getting/setting/etc... "/foo/bar" would result in operations being run on "/app/a/foo/bar" (from the server perspective). This feature is particularly useful in multi-tenant environments where each user of a particular ZooKeeper service could be rooted differently. This makes re-use much simpler as each user can code his/her application as if it were rooted at "/", while actual location (say /app/a) could be determined at deployment time.

**Comment by kaixinbaba** [comment]
你能理解我的意思就行了，我不是来教英文的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘骏佳 ***@***.***&gt;
发送时间: 2021年4月11日 23:10
收件人: HelloGitHub-Team/HelloZooKeeper ***@***.***&gt;
抄送: Jeff Xun ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[HelloGitHub-Team/HelloZooKeeper] 关于第二节的 chroot (#3)





 
这是我在 zk 官网看的，大致的意思就是在连接字符串后面添加的路径，zk 内部会做一个 chroot 操作，使得该连接的所有节点都以这个路径为根目录
  
Added in 3.2.0: An optional "chroot" suffix may also be appended to the connection string. This will run the client commands while interpreting all paths relative to this root (similar to the unix chroot command). If used the example would look like: "127.0.0.1:4545/app/a" or "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002/app/a" where the client would be rooted at "/app/a" and all paths would be relative to this root - ie getting/setting/etc... "/foo/bar" would result in operations being run on "/app/a/foo/bar" (from the server perspective). This feature is particularly useful in multi-tenant environments where each user of a particular ZooKeeper service could be rooted differently. This makes re-use much simpler as each user can code his/her application as if it were rooted at "/", while actual location (say /app/a) could be determined at deployment time.
