### ISSUE TITLE
关于zookeeper集群的疑问

### ISSUE THREAD

**Issue by liuhuihui01** [HelloGitHub-Team/HelloZooKeeper#4]
假设集群一共有3个节点
1、如果leader挂了，就无法再进去选举了？就无法再对外提供服务了是这样吗？
2、如果挂的是一个follower节点，是不是不影响集群，集群还是可以对外服务？如果是，那第二个follower也挂了呢？会影响吗？

**Comment by kaixinbaba** [comment]
无论挂的是 leader 还是 follower 只要另外两个节点可以使用，整个集群都可以重新选出新的 Leader 并对外提供服务，正常半数以上的策略的话，只要剩余可用节点数量大于总节点数的一半，就是可用的

**Comment by kaixinbaba** [comment]
刚刚那句话有点歧义，我重新说下，如果挂的那个节点是 Leader 才需要重新选举，挂的是 Follower 是不需要重新选举的

**Comment by liuhuihui01** [comment]
我的集群3个节点，Leader一直正常，然后两个follower连续挂了，是不是还是可以对外提供服务？

**Comment by liuhuihui01** [comment]
我的集群3个节点，Leader一直正常，然后两个follower连续挂了，是不是还是可以对外提供服务？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HelloGitHub-Team/HelloZooKeeper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 晚上9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HelloGitHub-Team/HelloZooKeeper] 关于zookeeper集群的疑问 (#4)





 
刚刚那句话有点歧义，我重新说下，如果挂的那个节点是 Leader 才需要重新选举，挂的是 Follower 是不需要重新选举的

**Comment by kaixinbaba** [comment]
3个节点挂了2个之后，是无法对外提供服务的

**Comment by liuhuihui01** [comment]
好的，明白了，谢谢

**Comment by kaixinbaba** [comment]

