### ISSUE TITLE
个人小建议

### ISSUE THREAD

**Issue by GuoXianSen** [HelloGitHub-Team/HelloZooKeeper#5]
感谢大佬无私的提供zk教程，在GitHub进行阅读的时候，您看是否可以在每一份Markdown文档的最后加上一个传送门，跳转到下一章节。

**Comment by ls0111** [comment]
和上面的小哥想法一致，感谢大佬的无私奉献~

**Comment by kaixinbaba** [comment]
已添加，感谢～
